# Docker-compose Version
version: '3'

# Definition of the services we need
services:
 
  # Data base service
  mysql:
    # Docker image of MySQL needed
    image: mysql:latest
    # Automatically relaunch the service in case of crash
    restart: always
    # Opening ports from the container to the PC
    ports: 
      - 3306:3306
    # Creation of the parameters required to connect to the database
    environment:
      # Data base name
      MYSQL_DATABASE: wordpress
      # User name allowed
      MYSQL_USER: wordpress
      # User Password
      MYSQL_PASSWORD: wordpress
      # Root password
      MYSQL_ROOT_PASSWORD: wordpress
    # Links between services
    networks: 
      # Link to wordpress
      - frontend
      # Link to phpMyAdmin
      - backend
    # Specify where to locally stock the data base
    volumes:
      # local_folder:online_folder
      - ./db_data:/var/lib/mysql
 
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  # Front-end service
  wordpress:
    # Other service(s) needed to work
    depends_on:
      - mysql
    # Docker image of Wordpress needed
    image: wordpress:latest
    # Specify where to locally stock wordpress files
    volumes:
      # local_folder:online_folder
      - ./wordpress:/var/www/html
    # Opening ports from the container to the PC
    ports:
      - "80:80"
    # Automatically relaunch the service in case of crash
    restart: always
    # Definition of the parameters used to connect to the database
    environment:
      # Data base server
      WORDPRESS_DB_HOST: mysql:3306
      # User name 
      WORDPRESS_DB_USER: wordpress
      # User password 
      WORDPRESS_DB_PASSWORD: wordpress
      # Data base name
      WORDPRESS_DB_NAME: wordpress
    # Links between sevices
    networks: 
      # Link to MySQL
      - frontend

# Define how to link services
networks: 
  frontend:
    # Allows Wordpress to communicate with MySQL
    driver: bridge
  backend:
    # Allows phpMyAdmin to communicate with MySQL
    driver: bridge

